package br.com.adamis.pessoa.entity;
// Generated 5 de mai. de 2021 22:52:41 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * Pessoas generated by hbm2java
 */
@Entity
@Table(name = "pessoas")
@Data
public class Pessoas {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Column(name = "nome")
	private String nome;
	
	@Column(name = "sexo", length = 2)
	private String sexo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_nasc", length = 19)
	private Date dataNasc;
	
	@Column(name = "telefone", length = 15)
	private String telefone;

}
