package br.com.adamis.usuarios.entity;
// Generated 6 de mai. de 2021 09:29:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios")
public class Usuarios implements java.io.Serializable {

	private static final long serialVersionUID = 8300436021894055473L;
	private Long id;
	private String usuario;
	private String senha;
	private String chave;
	private Integer pessoa;

	public Usuarios() {
	}

	public Usuarios(String usuario, String senha) {
		this.usuario = usuario;
		this.senha = senha;
	}

	public Usuarios(String usuario, String senha, String chave, Integer pessoa) {
		this.usuario = usuario;
		this.senha = senha;
		this.chave = chave;
		this.pessoa = pessoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "usuario", nullable = false)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "senha", nullable = false)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "chave")
	public String getChave() {
		return this.chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	@Column(name = "pessoa")
	public Integer getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Integer pessoa) {
		this.pessoa = pessoa;
	}

}
